---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-qadeploy-helloworld
  name: helloworld
  namespace: qadeploy
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-qadeploy-helloworld
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-qadeploy-helloworld
    spec:
      containers:
      - image: rakesh635/testhelloworld:{{BUILDNUMBER}}
        imagePullPolicy: Always
        name: helloworld
        ports:
        - containerPort: 8080
          name: 8080tcp80803
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
  name: helloworld-loadbalancer
  namespace: qadeploy
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 8080tcp80803
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-qadeploy-helloworld
  sessionAffinity: None
  type: LoadBalancer      
